name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest

    permissions:
      security-events: read

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

#    - name: Build and push the Docker image
#      run: |
#        # IMAGE_TAG=${{ github.sha }}
#        IMAGE_TAG=github-latest
#        docker build . --file Dockerfile --tag lionelschiepers/stockquote-node-api:$IMAGE_TAG
#        docker push lionelschiepers/stockquote-node-api:$IMAGE_TAG

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        tags:  lionelschiepers/stockquote-node-api:github-latest
        push: true

    - name: Docker Scout Quickview
      uses: docker/scout-action@v1
      with:
        command: quickview
        image: lionelschiepers/stockquote-node-api:github-latest

    - name: Docker Scout CVEs
      uses: docker/scout-action@v1
      with:
        command: cves
        image: lionelschiepers/stockquote-node-api:github-latest
        sarif-file: sarif.output.json
        summary: true

    - name: Docker Scout SBOM
      uses: docker/scout-action@v1
      with:
        command: sbom
        image: lionelschiepers/stockquote-node-api:github-latest
        output: sbom.json

    - name: Docker Scout Recommendations
      uses: docker/scout-action@v1
      with:
        command: recommendations
        image: lionelschiepers/stockquote-node-api:github-latest

    - name: Cat sarof
      run: |
        find . -name "sarif.output.json"
        cat sarif.output.json

    - name: Upload Docker Scout SARIF Report
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: sarif.output.json